const themes = [
  {
    name: 'catalog',
    foreground: '#121410',
    background: '#f4f5f1',
    muted: '#5f625b',
    bar: '#b9bbb2',
    link: '#243f9f',
    signal: '#d7ff35',
    hot: '#c51f50',
    cool: '#168f83',
  },
  {
    name: 'xerox',
    foreground: '#171713',
    background: '#eff1ee',
    muted: '#60635c',
    bar: '#b5b8b0',
    link: '#006c79',
    signal: '#ecff4a',
    hot: '#c3204f',
    cool: '#205ad4',
  },
  {
    name: 'receipt',
    foreground: '#18130f',
    background: '#fbf7eb',
    muted: '#6d6459',
    bar: '#d8cfbf',
    link: '#005f86',
    signal: '#e8ff3d',
    hot: '#d02f35',
    cool: '#16806d',
  },
  {
    name: 'fieldnote',
    foreground: '#172014',
    background: '#f2f6e8',
    muted: '#67705f',
    bar: '#c9d0ba',
    link: '#2556a3',
    signal: '#d9ff4a',
    hot: '#b92b52',
    cool: '#1d8975',
  },
  {
    name: 'blueprint',
    foreground: '#101828',
    background: '#eef5fb',
    muted: '#59677a',
    bar: '#c3d1df',
    link: '#0c5a9d',
    signal: '#e1ff38',
    hot: '#c12a5b',
    cool: '#008f95',
  },
  {
    name: 'risograph',
    foreground: '#20131b',
    background: '#fff1f2',
    muted: '#745f68',
    bar: '#e4c4cc',
    link: '#005d9a',
    signal: '#ddff2f',
    hot: '#d61d65',
    cool: '#0d8f7a',
  },
  {
    name: 'terminal-paper',
    foreground: '#111715',
    background: '#f1fff8',
    muted: '#5c6d66',
    bar: '#bcd6ca',
    link: '#006c84',
    signal: '#d4ff24',
    hot: '#c92c48',
    cool: '#167cbd',
  },
];

const theme = themes[Math.floor(Math.random() * themes.length)];

console.log('theme:', theme.name);

module.exports = {
  risks: [
    'dry mouth',
    'sudden death or dismemberment',
    'night sweats',
    'drowsiness',
    'dizziness',
    'hallucinations',
    'loud noises',
    'dry cough',
    'temporary loss of left and right',
    'unexplained soreness in one calf',
    'excessive blinking',
    'mild but persistent deja vu',
    `thinking it's Tuesday when it isn't`,
    `moments of intense nostalgia for events that never happened`,
    `saying "you too" when inappropriate`,
    `headphones catching on door handles`,
    `brief awareness of the void`,
    `questioning whether a hot dog is a sandwich`,
    `wondering where socks go`,
    `sudden interest in weather patterns`,
  ],
  theme,
  foreground: theme.foreground,
  background: theme.background,
};
